#!/bin/bash
set -e
gcc -o my_cat my_cat.c
diff <(./my_cat my_cat.c) my_cat.c
diff <(./my_cat < my_cat.c) my_cat.c
diff <(./my_cat  my_cat) my_cat.c || true
diff <(./my_cat < my_cat) my_cat.c || true
echo Done!
